"""EXP-FINAL-001: evidence-only Pareto synthesis. No model or portfolio execution."""
from __future__ import annotations
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
import pandas as pd
RESEARCH=Path(__file__).resolve().parent;R=RESEARCH/'results';M=RESEARCH/'manifests';C=RESEARCH/'contracts'/'exp_final_001.json';ARCHS=('LGBM_REGRESSION','LAMBDAMART')
def sha(p):h=hashlib.sha256();h.update(Path(p).read_bytes());return h.hexdigest()
def table(df,cols):
 x=df[cols].copy()
 for c in x:x[c]=x[c].map(lambda v:'N/A' if pd.isna(v) else f'{v:.4f}' if isinstance(v,(float,np.floating)) else str(v))
 return '| '+' | '.join(cols)+' |\n|'+'|'.join('---' for _ in cols)+'|\n'+'\n'.join('| '+' | '.join(map(str,r))+' |' for r in x.itertuples(index=False,name=None))
def main():
 c=json.loads(C.read_text());model=pd.read_csv(R/'EXP-MODEL-001_architecture_summary.csv').set_index('architecture');controlled=pd.read_csv(R/'EXP-MODEL-001_classification.csv').set_index('architecture');port=pd.read_csv(R/'EXP-PORT-001_classification.csv').set_index('architecture');cost=pd.read_csv(R/'EXP-PORT-001_cost_summary.csv');delay=pd.read_csv(R/'EXP-PORT-001_delay_summary.csv');cap=pd.read_csv(R/'EXP-PORT-001_capacity_summary.csv');rob=pd.read_csv(R/'EXP-ROBUST-001_classification.csv').set_index('architecture');conc=pd.read_csv(R/'EXP-ROBUST-001_concentration.csv').set_index('architecture');loo=pd.read_csv(R/'EXP-ROBUST-001_leave_one_period_out.csv');sim=pd.read_csv(R/'EXP-ROBUST-001_ranking_similarity.csv')
 rows=[]
 for a in ARCHS:
  mo=model.loc[a];po=port.loc[a];rr=rob.loc[a];cc=conc.loc[a];co100=float(cost[(cost.architecture==a)&(cost.cost_bps==100)].mean_net_return.iloc[0]);de2=float(delay[(delay.architecture==a)&(delay.delay_sessions==2)].mean_net_return.iloc[0]);fill=float(cap[(cap.architecture==a)&(cap.capital_try==50_000_000)&np.isclose(cap.adv_limit_pct,.10)].mean_fill_rate.iloc[0]);lo=loo[loo.architecture==a]
  ret='STRONG' if po.mean_net_return>0 and co100>0 and de2>0 and (lo.mean_net_return>0).all() else ('ACCEPTABLE' if po.mean_net_return>0 else 'WEAK')
  risk='STRONG' if po.worst_daily_maxdd>=-.30 and cc.top1_abs_pnl_share<=.25 and cc.largest_sector_abs_pnl_share<=.50 and po.mean_fill_rate>=.95 else ('ACCEPTABLE' if po.worst_daily_maxdd>=-.40 and cc.top1_abs_pnl_share<=.25 and po.mean_fill_rate>=.95 else 'WEAK')
  alpha='STRONG' if mo.mean_outer_rank_ic>0 and mo.median_outer_rank_ic>0 and mo.positive_fold_ratio>=.75 and mo.mean_ndcg_at_10>=.55 and controlled.loc[a].positive_delta_fold_ratio>=1 and rr.bootstrap_prob_ic_positive>=.75 else ('ACCEPTABLE' if mo.mean_outer_rank_ic>0 and mo.median_outer_rank_ic>0 and mo.mean_ndcg_at_10>=.55 and controlled.loc[a].positive_delta_fold_ratio>=1 and rr.bootstrap_prob_ic_positive>=.50 else 'WEAK')
  stability='STRONG' if rr.classification=='ROBUST' and rr.dimensions_passed==9 else ('ACCEPTABLE' if rr.classification=='ROBUST WITH CAVEATS' and rr.dimensions_passed>=8 else 'WEAK')
  cost_class='STRONG' if co100>0 and de2>0 and po.mean_turnover<=1.5 and fill>=.85 else ('ACCEPTABLE' if co100>0 and de2>0 else 'WEAK')
  complexity=c['dimensions']['COMPLEXITY'][a];data='ACCEPTABLE';hard=alpha=='WEAK' and rr.bootstrap_prob_ic_positive<.5 or co100<=0 or de2<=0 or po.mean_fill_rate<.95
  rows.append({'architecture':a,'RETURN':ret,'RISK':risk,'ALPHA':alpha,'STABILITY':stability,'COST':cost_class,'COMPLEXITY':complexity,'DATA_QUALITY':data,'hard_rejection':bool(hard),'carry_forward':not hard,'freeze_readiness':'NOT_READY' if hard else 'READY WITH CAVEATS'})
 dims=pd.DataFrame(rows)
 # Material tradeoffs prevent dominance: net return vs Sharpe, drawdown/sector vs stock concentration, and outer IC vs controlled/bootstrap alpha.
 dominance='BOTH NON-DOMINATED';decision='BOTH FINALISTS CARRIED FORWARD'
 rank_corr=float(sim.rank_correlation.mean());overlap=float(sim.top10_overlap.mean());ensemble='YES' if dims.carry_forward.all() and .2<=rank_corr<=.8 and overlap<.6 else ('MAYBE' if dims.carry_forward.all() else 'NO')
 gate='PASS' if dims.carry_forward.any() else 'FAIL'
 evidence_files=[R/'EXP-MODEL-001_architecture_summary.csv',R/'EXP-MODEL-001_classification.csv',R/'EXP-PORT-001_classification.csv',R/'EXP-PORT-001_cost_summary.csv',R/'EXP-PORT-001_delay_summary.csv',R/'EXP-PORT-001_capacity_summary.csv',R/'EXP-ROBUST-001_classification.csv',R/'EXP-ROBUST-001_concentration.csv',R/'EXP-ROBUST-001_leave_one_period_out.csv',R/'EXP-ROBUST-001_bootstrap.csv',R/'EXP-ROBUST-001_ranking_similarity.csv',RESEARCH/'contracts'/'exp_model_001.json',RESEARCH/'contracts'/'exp_port_001.json',RESEARCH/'contracts'/'exp_robust_001.json']
 hashes=pd.DataFrame([{'path':str(p.relative_to(RESEARCH)),'sha256':sha(p)} for p in evidence_files]);hashes.to_csv(R/'EXP-FINAL-001_evidence_hashes.csv',index=False);dims.to_csv(R/'EXP-FINAL-001_dimensions.csv',index=False)
 summary={'experiment_id':'EXP-FINAL-001','execution':'PASS','phase_j_gate':gate,'dominance':dominance,'decision':decision,'ensemble_justification':ensemble,'rank_correlation':rank_corr,'top10_overlap':overlap,'architectures':dims.to_dict('records'),'generated_at_utc':datetime.now(timezone.utc).isoformat()};(R/'EXP-FINAL-001_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf-8')
 sections=[('1. Executive Summary',f'Phase J: **{gate}**. **{dominance}**; **{decision}**.'),('2. Locked Decision Contract',f'`{C.name}` locked before synthesis; no numeric score or weights.'),('3. Evidence Sources',table(hashes,['path','sha256'])),('4. LGBM Regression Summary',table(dims[dims.architecture.eq('LGBM_REGRESSION')],list(dims.columns))),('5. LambdaMART Summary',table(dims[dims.architecture.eq('LAMBDAMART')],list(dims.columns))),('6. RETURN',table(dims,['architecture','RETURN'])),('7. RISK',table(dims,['architecture','RISK'])),('8. ALPHA',table(dims,['architecture','ALPHA'])),('9. STABILITY',table(dims,['architecture','STABILITY'])),('10. COST',table(dims,['architecture','COST'])),('11. COMPLEXITY',table(dims,['architecture','COMPLEXITY'])),('12. DATA QUALITY',table(dims,['architecture','DATA_QUALITY'])+'\n\nShared: price PASS FOR RESEARCH, survivor-universe and provider caveats, three price features, macro/fundamental excluded.'),('13. Pareto Dominance',f'**{dominance}**. Regression has stronger controlled/bootstrapped alpha, drawdown, sector concentration and simplicity; LambdaMART has higher whole-procedure mean IC, positive-fold ratio, Sharpe and lower single-stock concentration. These are material tradeoffs.'),('14. Finalist Decision',f'**{decision}**. No hard rejection condition fired.'),('15. Ensemble Eligibility',f'**{ensemble}** — rank correlation {rank_corr:.4f}, Top-10 overlap {overlap:.4f}; no ensemble was built or backtested.'),('16. Freeze Readiness',table(dims,['architecture','freeze_readiness'])),('17. Known Caveats','Shared mom_63 dependence; Regression O1/time sensitivity and higher top-1 stock share; LambdaMART sector concentration and lower bootstrap P(IC>0); dependent folds/cohorts and shared data limitations.'),('18. Tests','Evidence-hash, no-fit/no-optimization, Pareto-rule and production-integrity tests required.'),('19. Production Integrity','Final protected-production hash verification required.'),('20. MASTER_PLAN\'e göre SINGLE NEXT BEST ACTION','Because both finalists survive and ensemble justification is YES, review and authorize only optional Phase K rank-average ensemble experiment; do not build it automatically.')]
 (R/'EXP-FINAL-001_report.md').write_text('# EXP-FINAL-001 — PARETO FINALIST DECISION\n\n'+'\n\n'.join(f'## {h}\n\n{b}' for h,b in sections),encoding='utf-8');files=sorted(R.glob('EXP-FINAL-001_*'));M.mkdir(exist_ok=True);(M/'EXP-FINAL-001_manifest.json').write_text(json.dumps({'contract_sha256':sha(C),'code_sha256':sha(Path(__file__)),'evidence':{str(p.relative_to(RESEARCH)):sha(p) for p in evidence_files},'files':{p.name:sha(p) for p in files}},indent=2),encoding='utf-8');print(json.dumps(summary,indent=2))
if __name__=='__main__':main()
